packages:
  - ./common
  - ./core
  - ./drivers
  - ./examples
minimumReleaseAge: 4320 # 3 days in minutes, minimumReleaseAge protects against supply chain attacks.
# minimumReleaseAgeStrict: true, will be needed to maintain pnpm 10 behavior when pnpm 11 is adopted.
minimumReleaseAgeExclude:
  - '@vertesia/*'
  - '@llumiverse/*'
  - 'protobufjs@7.5.5'
