packages:
  - ./common
  - ./core
  - ./drivers
  - ./examples
minimumReleaseAge: 1440 # 1 day in minutes, minimumReleaseAge protects against supply chain attacks.
minimumReleaseAgeExclude:
- '@vertesia/*'
- '@llumiverse/*'