export const TEXT_EXTERNALIZATION_PROCESSOR_ID = 'externalize-text';
export const TEXT_EXTERNALIZATION_PROCESSOR_VERSION = '1';
export const MAX_TEXT_EXTERNALIZATION_BYTES = 32 * 1024 * 1024;
export const MAX_TEXT_EXTERNALIZATION_BLOCKS = 4096;
