name: (lint) lint codebase

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24.15.0
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
